# Generated by Django 5.0.2 on 2024-03-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='product_images',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='donation',
            name='product_images',
            field=models.ImageField(default=123, upload_to='images/'),
            preserve_default=False,
        ),
    ]
