# Generated by Django 5.0.2 on 2024-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='product_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
