# Generated by Django 5.0.2 on 2024-03-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ngo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NGO',
        ),
    ]
