# Generated by Django 5.0.2 on 2024-03-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ngo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NGO',
        ),
    ]
