# Generated by Django 5.0.2 on 2024-04-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_ngoprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ngo')),
            ],
        ),
    ]
