# Generated by Django 5.0.2 on 2024-04-11 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_createcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
