# Generated by Django 5.0.2 on 2024-04-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_donor_latitude_donor_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='other_products',
            field=models.TextField(max_length=100),
        ),
    ]
