# Generated by Django 5.0.4 on 2024-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_ngoprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
