# Generated by Django 5.0.4 on 2024-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_volunteer_latitude_volunteer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcampaign',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
