# Generated by Django 5.0.4 on 2024-05-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_createcampaign_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONATED', 'Donated')], default='PENDING', max_length=20),
        ),
    ]
